version: '3'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      app-network:
        aliases:
          - matric

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.angular
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - app-network

volumes:
  mongodata:

networks:
  app-network:
    driver: bridge