version: '3.10'

services:
  access-5g:
    build:
      context: .
      dockerfile: access-5g/Dockerfile
    ports:
      - 10001:10001

  access-wifi:
    build:
      context: .
      dockerfile: access-wifi/Dockerfile
    ports:
      - 10002:10002

  access-agg:
    build:
      context: .
      dockerfile: access-aggregator/Dockerfile
    ports:
      - 10000:10000
    networks:
      default:
        aliases:
          - ap_aggregator
